kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: minio-sc
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /Users/agro/microk8s/storage/minio
volumeBindingMode: WaitForFirstConsumer
